### ISSUE TITLE
Launch permissions

### ISSUE THREAD

**Issue by markuz449** [nathanhollows/NuggetNav#12]
When the app is first launched you need it to ask the user for access to their location. Should also implement a view for when there is no wifi or location

**Comment by nathanhollows** [comment]
The wifi issue should be solved by storing the location data locally ( #7 ) and updating that when wifi is available. Additionally, the map and store data can also be cached. This should be it's own issue.

I'll take a look at the permissions

**Comment by nathanhollows** [comment]
This checks for permissions instead of crashing. The next step is to enable `locationComponent` if this is successful
